"""
writer.py — записывает рабочие серверы в файлы.

Простыми словами:
  Берём список проверенных серверов и раскладываем по файлам:
  - Все вместе (VLESS_WORKING.txt)
  - По типу протокола (VLESS_ONLY.txt, VMESS_ONLY.txt и т.д.)
  - Топ-50 самых быстрых (TOP50.txt)
  - Топ-50 самых надёжных (TOP50_RELIABLE.txt) ← НОВОЕ
  - Статистика (stats.json)

  Каждый сервер теперь получает рейтинг надёжности ⭐⭐⭐
  на основе истории предыдущих проверок.
"""

import json
import logging
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import unquote, urlparse
from zoneinfo import ZoneInfo

sys.path.insert(0, str(Path(__file__).parent.parent))
sys.path.insert(0, str(Path(__file__).parent))
import config as cfg
from collector import is_russia_bypass

log = logging.getLogger("writer")
OUTPUT_DIR = Path(__file__).parent.parent / "output"


# ── Вспомогательные ─────────────────────────────────────────────────────────────

def _get_host(config_str: str) -> str:
    """Вытаскивает hostname из строки конфига."""
    try:
        if config_str.lower().startswith("vmess://"):
            import base64, json as _j
            b64 = config_str[8:].split("#")[0].split("?")[0]
            b64 += "=" * (-len(b64) % 4)
            return str(_j.loads(base64.b64decode(b64).decode("utf-8", errors="ignore")).get("add", ""))
        return urlparse(config_str).hostname or ""
    except Exception:
        return ""


def _clean_label(cfg_str: str, latency: int, geo: dict, score: float) -> str:
    """
    Собирает читаемую метку для конфига.

    Пример результата:
      vless://...#🇩🇪 Germany (Frankfurt) 🔒 ⭐⭐⭐⭐ | 142ms
    """
    base, _, label = cfg_str.partition("#")
    label = unquote(label).strip()
    label = re.sub(r"\s*\|\s*\d+ms", "", label)       # убираем старую задержку
    label = re.sub(r"\s*⭐+·*", "", label)             # убираем старые звёзды
    label = re.sub(r"\s*🆕", "", label)                # убираем старый маркер

    flag    = geo.get("flag", "🌐")
    country = geo.get("country", "")
    city    = geo.get("city", "")
    tls     = " 🔒" if geo.get("tls_ok") else ""

    # Рейтинг надёжности
    if score < 0:
        stars = " 🆕"                      # новый сервер — нет истории
    else:
        s = round(score * 5)
        stars = " " + "⭐" * s + "·" * (5 - s)

    if country and country != "Unknown":
        loc = f"{flag} {country}"
        if city:
            loc += f" ({city})"
    elif label:
        loc = label
    else:
        loc = "server"

    return f"{base}#{loc}{tls}{stars} | {latency}ms"


def _header(title: str, count: int, now_msk: datetime, raw_url: str = "") -> list[str]:
    """Строки заголовка файла подписки."""
    now_utc = datetime.now(timezone.utc)
    lines = [
        f"# profile-title: {title}",
        f"# profile-update-interval: 1",
        f"# Date/Time: {now_utc.strftime('%Y-%m-%d')} / {now_msk.strftime('%H:%M')} (Moscow)",
        f"# Количество: {count}",
        f"# Generated by: vless-collector (GitHub Actions)",
    ]
    if raw_url:
        lines.append(f"# URL: {raw_url}")
    lines.append("")
    return lines


# ── Основная функция ──────────────────────────────────────────────────────────

def write_all_outputs(
    working:    list[tuple[str, int]],
    geo_map:    dict | None = None,
    tls_map:    dict | None = None,
    score_map:  dict | None = None,
    ru_keys:    set[str] | None = None,  # ключи конфигов из RU-источников
) -> dict:
    """
    Записывает все выходные файлы.

    working    — [(config_string, latency_ms), ...]  отсортировано по latency
    geo_map    — {host: {country, city, flag, ...}}
    tls_map    — {host: True/False}
    score_map  — {host: float}  рейтинг надёжности из истории
    """
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    now_msk   = datetime.now(ZoneInfo("Europe/Moscow"))
    geo_map   = geo_map   or {}
    tls_map   = tls_map   or {}
    score_map = score_map or {}
    ru_keys   = ru_keys   or set()

    # ── Разбивка по протоколам + RU_BYPASS ───────────────────────────────────
    buckets: dict[str, list[tuple[str, int]]] = {
        "all": [], "vless": [], "vmess": [], "trojan": [],
        "hysteria": [], "ss": [], "other": [],
        "ru_bypass": [],   # серверы для обхода РКН/ТСПУ
    }
    country_stats:  dict[str, int] = {}
    tls_confirmed = 0

    for config_str, lat in working:
        low = config_str.lower()
        if   low.startswith("vless://"):    buckets["vless"].append((config_str, lat))
        elif low.startswith("vmess://"):    buckets["vmess"].append((config_str, lat))
        elif low.startswith("trojan://"):   buckets["trojan"].append((config_str, lat))
        elif low.startswith(("hysteria2://","hy2://")): buckets["hysteria"].append((config_str, lat))
        elif low.startswith("ss://"):       buckets["ss"].append((config_str, lat))
        else:                               buckets["other"].append((config_str, lat))
        buckets["all"].append((config_str, lat))

        # RU_BYPASS: конфиг попадает если:
        #   1. Пришёл из RU-источника  ИЛИ
        #   2. Является Reality/XTLS по параметрам
        config_key = config_str.split("#")[0].rstrip("?& ")
        if config_key in ru_keys or is_russia_bypass(config_str):
            buckets["ru_bypass"].append((config_str, lat))

        host = _get_host(config_str)
        geo  = geo_map.get(host, {})
        cc   = geo.get("country", "Unknown")
        country_stats[cc] = country_stats.get(cc, 0) + 1
        if tls_map.get(host):
            tls_confirmed += 1

    # ── Топ-50 надёжных (сортировка по рейтингу, потом по задержке) ──────────
    def reliability_sort_key(item: tuple[str, int]):
        config_str, lat = item
        host  = _get_host(config_str)
        score = score_map.get(host, -1.0)
        # -score чтобы высокий рейтинг шёл первым, при равном — меньшая задержка
        return (-score if score >= 0 else 1.0, lat)

    top50_reliable = sorted(buckets["all"], key=reliability_sort_key)[:50]

    # ── Запись файлов ─────────────────────────────────────────────────────────
    raw_base = cfg.RAW_BASE

    files_cfg = [
        ("VLESS_WORKING.txt", "all",       "✅ All Working Servers | Auto-collected"),
        ("RU_BYPASS.txt",     "ru_bypass", "🇷🇺 RU Bypass (Reality+XTLS) | Обход РКН/ТСПУ"),
        ("VLESS_ONLY.txt",    "vless",     "🔷 VLESS Only | Auto-collected"),
        ("VMESS_ONLY.txt",    "vmess",     "🔶 VMess Only | Auto-collected"),
        ("TROJAN_ONLY.txt",   "trojan",    "🐴 Trojan Only | Auto-collected"),
        ("HYSTERIA_ONLY.txt", "hysteria",  "⚡ Hysteria2 Only | Auto-collected"),
        ("SS_ONLY.txt",       "ss",        "🔲 Shadowsocks Only | Auto-collected"),
    ]

    written: dict[str, int] = {}

    for filename, bucket_key, title in files_cfg:
        entries = buckets[bucket_key]
        if not entries:
            continue
        full_title = f"{title} | {now_msk.strftime('%Y-%m-%d %H:%M')} MSK"
        lines = _header(full_title, len(entries), now_msk, f"{raw_base}/{filename}")
        for config_str, lat in entries:
            host  = _get_host(config_str)
            geo   = dict(geo_map.get(host, {}))
            geo["tls_ok"] = tls_map.get(host, False)
            score = score_map.get(host, -1.0)
            lines.append(_clean_label(config_str, lat, geo, score))
        (OUTPUT_DIR / filename).write_text("\n".join(lines) + "\n", encoding="utf-8")
        written[filename] = len(entries)
        log.info("  💾 %-26s %d конфигов", filename, len(entries))

    # ── TOP-50 быстрых ────────────────────────────────────────────────────────
    top50 = buckets["all"][:50]
    if top50:
        lines = _header(
            f"🏆 TOP-50 Fastest | {now_msk.strftime('%Y-%m-%d %H:%M')} MSK",
            len(top50), now_msk, f"{raw_base}/TOP50.txt"
        )
        for config_str, lat in top50:
            host  = _get_host(config_str)
            geo   = dict(geo_map.get(host, {}))
            geo["tls_ok"] = tls_map.get(host, False)
            lines.append(_clean_label(config_str, lat, geo, score_map.get(host, -1.0)))
        (OUTPUT_DIR / "TOP50.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")
        written["TOP50.txt"] = len(top50)
        log.info("  💾 %-26s %d конфигов", "TOP50.txt", len(top50))

    # ── TOP-50 надёжных (новинка!) ────────────────────────────────────────────
    if top50_reliable:
        lines = _header(
            f"🛡 TOP-50 Most Reliable | {now_msk.strftime('%Y-%m-%d %H:%M')} MSK",
            len(top50_reliable), now_msk, f"{raw_base}/TOP50_RELIABLE.txt"
        )
        for config_str, lat in top50_reliable:
            host  = _get_host(config_str)
            geo   = dict(geo_map.get(host, {}))
            geo["tls_ok"] = tls_map.get(host, False)
            lines.append(_clean_label(config_str, lat, geo, score_map.get(host, -1.0)))
        (OUTPUT_DIR / "TOP50_RELIABLE.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")
        written["TOP50_RELIABLE.txt"] = len(top50_reliable)
        log.info("  💾 %-26s %d конфигов", "TOP50_RELIABLE.txt", len(top50_reliable))

    # ── stats.json ────────────────────────────────────────────────────────────
    latencies = [lat for _, lat in buckets["all"]]
    stats = {
        "updated_utc":   datetime.now(timezone.utc).isoformat(),
        "updated_msk":   now_msk.isoformat(),
        "total_working": len(buckets["all"]),
        "tls_confirmed": tls_confirmed,
        "by_protocol": {
            "vless":     len(buckets["vless"]),
            "vmess":     len(buckets["vmess"]),
            "trojan":    len(buckets["trojan"]),
            "hysteria":  len(buckets["hysteria"]),
            "ss":        len(buckets["ss"]),
            "other":     len(buckets["other"]),
            "ru_bypass": len(buckets["ru_bypass"]),
        },
        "latency": {
            "min_ms": min(latencies) if latencies else 0,
            "avg_ms": sum(latencies) // len(latencies) if latencies else 0,
            "max_ms": max(latencies) if latencies else 0,
            "p50_ms": sorted(latencies)[len(latencies)//2] if latencies else 0,
            "p90_ms": sorted(latencies)[int(len(latencies)*0.9)] if latencies else 0,
        },
        "top_countries": dict(sorted(country_stats.items(), key=lambda x: -x[1])[:15]),
        "files":         written,
        "raw_base":      raw_base,
    }
    (OUTPUT_DIR / "stats.json").write_text(
        json.dumps(stats, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    log.info("  💾 %-26s записан", "stats.json")
    return stats
